### PR TITLE
Replace build & push with custom action

### PR DESCRIPTION
**Pull request by MatthewCane**
The current Workflow is using deprecated features, this change replaces it with a custom action that can be maintained from a single repo.

### CODE REVIEW

**Comment by mrdaniellewis** [comment]
There are a few repos that will need this.

Does this build an arm64 image as well?

**Comment by mrdaniellewis** [comment]
But I like it.  Much easier

**Comment by MatthewCane** [comment]
It only builds x86 at the moment, but I'm sure I can have it build both if that is something you would want. I will roll it out across more repos once this is merged and I can see everything is working as intended.

**Comment by mrdaniellewis** [comment]
Yes, we really need arm64.  As almost everyone (but me) has an arm mac, it really slows down local development if the containers are only x86 and it has to emulate.

**Comment by mrdaniellewis** [comment]
As an aside, it would be great if we could use github actions for the private ECR as well, as it is marginally easier to setup over adding a JenkinsFile and setting up the jenkins project.

But I think there were come privacy (or was it cost) concerns over doing that.

**Comment by MatthewCane** [comment]
Okay @mrdaniellewis I have updated the action to also build arm64 images. I've tested it and it seems to be working but ECR isn't particularly transparent about what architectures are being pushed up. I am planning on writing a private ECR push action as well, I will create a ticket now 🙂

**Comment by mrdaniellewis** [comment]
That's brilliant.  The new action will be so much easier.

I think `docker manifest inspect IMAGE_LOCATION` tells you.

**Pull request merged**
